const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const store = { get(k, f){ try { const r = localStorage.getItem(k); return r ? JSON.parse(r) : f; } catch { return f; } }, set(k,v){ localStorage.setItem(k, JSON.stringify(v)); } };
const viewMeta = { dashboard: { title: "Dashboard", subtitle: "Build, write, and prompt from one mobile-first interface." }, notes: { title: "Notes", subtitle: "Store notes locally with search, edit, and export." }, gemini: { title: "Gemini Helper", subtitle: "Use your own API key and model from a single clean panel." }, prompts: { title: "Prompt Lab", subtitle: "Compose structured prompts for better AI output." } };
const app = { notes: store.get("neuro_notes", []), route: (location.hash || "#dashboard").replace("#", ""), theme: store.get("neuro_theme", "light") };
function escapeHtml(value = "") { return String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;"); }
function formatDate(ts) { try { return new Date(ts).toLocaleString(); } catch { return ""; } }
function syncStats() { const statsText = $("#statsText"); const dashNotesCount = $("#dashNotesCount"); if (statsText) statsText.textContent = `${app.notes.length} notes saved`; if (dashNotesCount) dashNotesCount.textContent = app.notes.length; }
function saveNotes() { store.set("neuro_notes", app.notes); syncStats(); }
function setRoute(route) { const safeRoute = viewMeta[route] ? route : "dashboard"; app.route = safeRoute; location.hash = safeRoute; renderRoute(); }
function renderRoute() { const safeRoute = viewMeta[app.route] ? app.route : "dashboard"; const meta = viewMeta[safeRoute]; $$(".view").forEach((view) => view.classList.toggle("active", view.dataset.view === safeRoute)); $$(".nav-btn").forEach((btn) => btn.classList.toggle("active", btn.dataset.route === safeRoute)); const title = $("#pageTitle"); const subtitle = $("#pageSubtitle"); if (title) title.textContent = meta.title; if (subtitle) subtitle.textContent = meta.subtitle; }
function resetNoteForm() { const title = $("#noteTitle"); const body = $("#noteBody"); const editing = $("#editingNoteId"); if (title) title.value = ""; if (body) body.value = ""; if (editing) editing.value = ""; }
function fillNoteForm(note) { $("#noteTitle").value = note.title || ""; $("#noteBody").value = note.body || ""; $("#editingNoteId").value = note.id || ""; setRoute("notes"); window.scrollTo({ top: 0, behavior: "smooth" }); }
function deleteNote(id) { app.notes = app.notes.filter((note) => note.id !== id); saveNotes(); renderNotes(); }
function renderNotes() { const list = $("#notesList"); const search = $("#searchNotes"); if (!list) return; const query = (search?.value || "").trim().toLowerCase(); const filtered = app.notes.filter((note) => { const haystack = `${note.title || ""} ${note.body || ""}`.toLowerCase(); return haystack.includes(query); }); if (!filtered.length) { list.innerHTML = `<article class="note-card"><h4>No notes found</h4><p>Create your first note or change the search text.</p></article>`; return; } list.innerHTML = filtered.map((note) => `<article class="note-card"><h4>${escapeHtml(note.title)}</h4><div class="note-meta">Updated ${escapeHtml(formatDate(note.updatedAt))}</div><p>${escapeHtml(note.body)}</p><div class="note-actions"><button class="neu-btn edit-note" data-id="${note.id}" type="button">Edit</button><button class="neu-btn delete-note" data-id="${note.id}" type="button">Delete</button></div></article>`).join(""); $$(".edit-note").forEach((btn) => { btn.addEventListener("click", () => { const note = app.notes.find((item) => item.id === btn.dataset.id); if (note) fillNoteForm(note); }); }); $$(".delete-note").forEach((btn) => { btn.addEventListener("click", () => deleteNote(btn.dataset.id)); }); }
function exportNotes() { const blob = new Blob([JSON.stringify(app.notes, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "neurostack-notes.json"; link.click(); URL.revokeObjectURL(url); }
function buildPrompt() { const role = $("#pbRole")?.value.trim() || ""; const goal = $("#pbGoal")?.value.trim() || ""; const audience = $("#pbAudience")?.value.trim() || ""; const tone = $("#pbTone")?.value.trim() || ""; const context = $("#pbContext")?.value.trim() || ""; const constraints = $("#pbConstraints")?.value.trim() || ""; const format = $("#pbFormat")?.value.trim() || ""; const lines = [ role ? `You are ${role}.` : "", goal ? `Primary goal: ${goal}.` : "", audience ? `Target audience: ${audience}.` : "", tone ? `Tone: ${tone}.` : "", context ? `Context: ${context}` : "", constraints ? `Constraints: ${constraints}` : "", format ? `Output format: ${format}` : "", "Respond clearly, specifically, and with practical detail." ].filter(Boolean); const out = $("#promptOutput"); if (out) out.value = lines.join("\n"); }
function clearPromptBuilder() { ["#pbRole", "#pbGoal", "#pbAudience", "#pbTone", "#pbContext", "#pbConstraints", "#pbFormat", "#promptOutput"].forEach((id) => { const el = $(id); if (el) el.value = ""; }); }
function applyTheme(theme) { document.documentElement.setAttribute("data-theme", theme); app.theme = theme; store.set("neuro_theme", theme); const toggle = $("#themeToggle"); if (toggle) toggle.textContent = theme === "dark" ? "â˜€ï¸ Light" : "ðŸŒ™ Dark"; }
function toggleTheme() { applyTheme(app.theme === "dark" ? "light" : "dark"); }
function bindEvents() { $$(".nav-btn").forEach((btn) => { btn.addEventListener("click", () => setRoute(btn.dataset.route)); }); $$(".jump-btn").forEach((btn) => { btn.addEventListener("click", () => setRoute(btn.dataset.jump)); }); window.addEventListener("hashchange", () => { app.route = (location.hash || "#dashboard").replace("#", ""); renderRoute(); }); const noteForm = $("#noteForm"); if (noteForm) { noteForm.addEventListener("submit", (event) => { event.preventDefault(); const title = $("#noteTitle")?.value.trim() || ""; const body = $("#noteBody")?.value.trim() || ""; const editingId = $("#editingNoteId")?.value || ""; if (!title || !body) return; if (editingId) { app.notes = app.notes.map((note) => note.id === editingId ? { ...note, title, body, updatedAt: Date.now() } : note); } else { app.notes.unshift({ id: (window.crypto && crypto.randomUUID) ? crypto.randomUUID() : String(Date.now()), title, body, updatedAt: Date.now() }); } saveNotes(); resetNoteForm(); renderNotes(); }); } $("#resetNote")?.addEventListener("click", resetNoteForm); $("#searchNotes")?.addEventListener("input", renderNotes); $("#exportNotes")?.addEventListener("click", exportNotes); $("#buildPrompt")?.addEventListener("click", buildPrompt); $("#clearPrompt")?.addEventListener("click", clearPromptBuilder); $("#copyPrompt")?.addEventListener("click", async () => { const text = $("#promptOutput")?.value || ""; if (!text) return; await navigator.clipboard.writeText(text); }); $("#clearAllData")?.addEventListener("click", () => { localStorage.removeItem("neuro_notes"); localStorage.removeItem("gemini_settings"); localStorage.removeItem("neuro_theme"); app.notes = []; saveNotes(); renderNotes(); resetNoteForm(); applyTheme("light"); }); $("#themeToggle")?.addEventListener("click", toggleTheme); }
function init() { applyTheme(app.theme || "light"); syncStats(); renderRoute(); renderNotes(); bindEvents(); }
document.addEventListener("DOMContentLoaded", init);
